title:              "Hseong"
tagline:            "Exploring Digital Marketing"
email:              "carolina9684@gmail.com"
description:        "디지털마케팅 데이터 활용 및 시각화"
author:             "혜성"
baseurl:            "/"
url:                "https://hseong.co.kr/"
locale:             "ko_KR"
thumbnail:          "/img/blog-thumbnail.png"

# Social Profiles
instagram_username: instagram_northstar_met
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: https-hseong-co-kr
